### PR TITLE
Robot 36 color correction

### PR DESCRIPTION
**Pull request by unixispower**
I have corrected the inter-channel frequencies to match what is described in the SSTV [Handbook Chapter 4, Page 4](http://www.sstv-handbook.com/download/sstv_04.pdf).

### CODE REVIEW

**Comment by dnet** [comment]
What decoder(s) have you tested the output with? Could you make a simple table like this below? I'd be mostly interested in results with MMSSTV, slowrx and other widely used decoders, but every data point is important.

| decoder | old version (`master`) | new version (`patch-1`) |
| --- | --- | --- |
| decoder1 | works | doesn't work |
| decoder2 | works | works |
| decoder3 | doesn't work | doesn't work |
| decoder4 | doesn't work | works |

Markdown source for easier copying:

```
| decoder | old version (`master`) | new version (`patch-1`) |
| --- | --- | --- |
| decoder1 | works | doesn't work |
| decoder2 | works | works |
| decoder3 | doesn't work | doesn't work |
| decoder4 | doesn't work | works |
```

**Comment by unixispower** [comment]
I ran some more tests with the following image:

card

| decoder | old version (`master`) | new version (`patch-1`) |
| --- | --- | --- |
| Robot36 v1.35 (Android) |  robot36-1 35-master | robot36-1 35-patch-1 |
| QSSTV v9.2.4 (Linux) | qsstv-9 2 4-master | qsstv-9 2 4-patch-1 |
| slowrx v0.01 alpha (Linux) | slowrx-0 01-master  | slowrx-0 01-patch-1  |

The patch fixed Robot36, but not QSSTV or slowrx. I suspect QSSTV and slowrx are implemented to use a fixed color order of CrCb rather than detecting the correct channel from the inter-channel frequency sentinel.

A potential fix is to reorder the channels in pySSTV to be sent CrCb and keep the pre-patch inter-channel frequency array. I can try implementing these changes and testing again.

**Comment by unixispower** [comment]
I changed the order of the channels in the scanline to CrCb. Since PIL doesn't support YCrCb (only YCbCr) I reversed the order the channels are written into the scanline by inverting the color channel index. This seems to have pleased all the decoders I tested against. Here is the updated patch-1 column:

| decoder | new version (`patch-1`) |
| --- | --- |
| Robot36 v1.35 (Android) | robot36-1 35-patch-1 |
| QSSTV v9.2.4 (Linux) | qsstv-9 2 4-patch-1 |
| slowrx v0.01 alpha (Linux) | slowrx-0 01-patch-1 |

**Comment by dnet** [comment]
Nice job, thanks! 👍

**Comment by dnet** [comment]
I published [v0.3.1](https://github.com/dnet/pySSTV/releases/tag/v0.3.1) with this fix in it.

**Pull request merged**
